// Auto-generated from shophub.com Shopify data
export const SEED_PRODUCTS = [
  {
    "title": "Kanjivaram Silk Saree – Orange Radiance",
    "slug": "kanjivaram-silk-saree-orange-radiance",
    "description": "Make a statement of timeless elegance with this stunning Kanjivaram Silk Saree in a vibrant Bright Orange hue. Woven with intricate floral zari motifs across the body, this saree beautifully reflects the richness of traditional craftsmanship. The highlight of this masterpiece is its luxurious contrast border adorned with exquisite paisley motifs , enhanced with delicate stone and diamond embellishments that add a subtle sparkle. The rich zari weaving and lustrous silk texture create a regal look",
    "fullDescription": "<p>Make a statement of timeless elegance with this stunning <strong>Kanjivaram Silk Saree</strong> in a vibrant <strong>Bright Orange</strong> hue. Woven with intricate floral zari motifs across the body, this saree beautifully reflects the richness of traditional craftsmanship.</p>\n<p>The highlight of this masterpiece is its luxurious <strong>contrast border adorned with exquisite paisley motifs</strong>, enhanced with delicate <strong>stone and diamond embellishments</strong> that add a subtle sparkle. The rich zari weaving and lustrous silk texture create a regal look, making it a perfect choice for weddings, festive celebrations, receptions, and grand occasions.</p>\n<p>Paired with a matching woven blouse fabric, this saree is designed for women who appreciate heritage weaves with a touch of contemporary glamour.<br><br></p>\n<h3>Product Highlights</h3>\n<ul>\n<li>Premium Kanjivaram Silk Saree</li>\n<li>Vibrant Bright Orange Shade</li>\n<li>Rich Floral Zari Weaving Across the Body</li>\n<li>Grand Paisley Motif Border</li>\n<li>Intricate Stone &amp; Diamond Embellishments</li>\n<li>Luxurious Traditional Weaving</li>\n<li>Elegant Festive &amp; Wedding Wear</li>\n<li>Soft Lustrous Finish</li>\n<li>Matching Woven Blouse Included<br><br><meta charset=\"UTF-8\">\n<h3>Fabric Details</h3>\n<ul>\n<li>\n<strong>Saree Fabric:</strong> Kanjivaram Silk</li>\n<li>\n<strong>Work:</strong> Rich Zari Weaving, Stone &amp; Diamond Work</li>\n<li>\n<strong>Body Design:</strong> Floral Weaving Pattern</li>\n<li>\n<strong>Border Design:</strong> Grand Paisley Motif Border with Embellishments</li>\n<li>\n<strong>Blouse:</strong> Matching Kanjivaram Silk Blouse Fabric (Unstitched)</li>\n</ul>\n<br>\n</li>\n<li>\n<h3>Blouse Note</h3>\n<p><em>The model is wearing a stitched blouse for styling purposes. The saree comes with an unstitched blouse piece in matching fabric and design.</em></p>\n</li>\n</ul>",
    "salePrice": 2780,
    "regularPrice": 4500,
    "category": "Silk",
    "status": "Available",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC2443.jpg?v=1781861351",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC2443.jpg?v=1781861351",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC2434.jpg?v=1781861350",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC2446.jpg?v=1781861351",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC2457_68722272-6498-4cf0-9048-29aba8ad9e7d.jpg?v=1781861582"
    ],
    "tags": [
      "Bridal Saree",
      "Bright Orange Saree",
      "Designer Kanjivaram Saree",
      "Diamond Work Saree",
      "Festive Saree",
      "Kanjivaram Silk Saree",
      "Luxury Saree",
      "Paisley Border Saree",
      "ShopHub",
      "Stone Work Saree",
      "Traditional Silk Saree",
      "Wedding Saree",
      "Zari Weaving Saree"
    ],
    "featured": true,
    "bestSeller": true,
    "newArrival": false,
    "rating": 4,
    "reviewCount": 3,
    "createdAt": "2026-06-25T07:55:30.095Z"
  },
  {
    "title": "Pure Modal Satin Silk Saree – Kumkum Maroon",
    "slug": "pure-modal-satin-silk-saree-kumkum-maroon",
    "description": "A rich blend of tradition and elegance, this Pure Modal Satin Silk Saree comes in a beautiful Kumkum Maroon shade that exudes timeless grace. The saree features an intricately woven checks body adorned with delicate mirror work , adding just the right touch of sparkle. The highlight of this masterpiece is its stunning Ajrak print pallu , enhanced with a classic Lakdi Patta design , complemented by a same-tone piping border and an elegant woven floral border . The luxurious satin silk texture off",
    "fullDescription": "<p>A rich blend of tradition and elegance, this <strong>Pure Modal Satin Silk Saree</strong> comes in a beautiful <strong>Kumkum Maroon</strong> shade that exudes timeless grace. The saree features an intricately woven <strong>checks body</strong> adorned with delicate <strong>mirror work</strong>, adding just the right touch of sparkle.</p>\n<p>The highlight of this masterpiece is its stunning <strong>Ajrak print pallu</strong>, enhanced with a classic <strong>Lakdi Patta design</strong>, complemented by a <strong>same-tone piping border</strong> and an elegant <strong>woven floral border</strong>. The luxurious satin silk texture offers a graceful drape and a subtle sheen, making it perfect for festive celebrations, weddings, and special occasions.</p>\n<p>Paired with a matching <strong>Ajrak print blouse fabric featuring a woven border</strong>, this saree creates a complete and sophisticated ethnic look.</p>\n<h4>Product Highlights</h4>\n<ul>\n<li>Pure Modal Satin Silk Saree</li>\n<li>Elegant Kumkum Maroon Shade</li>\n<li>Traditional Ajrak Print Pallu</li>\n<li>Classic Lakdi Patta Design</li>\n<li>Woven Checks Body</li>\n<li>Delicate Mirror Work Detailing</li>\n<li>Same Tone Piping Border</li>\n<li>Rich Woven Floral Border</li>\n<li>Soft, Lightweight &amp; Graceful Drape</li>\n<li>Matching Ajrak Print Blouse with Woven Border<br><br><meta charset=\"UTF-8\">\n<h4>Fabric Details</h4>\n<ul>\n<li>\n<strong>Saree Fabric:</strong> Pure Modal Satin Silk</li>\n<li>\n<strong>Work:</strong> Weaving Checks, Mirror Work</li>\n<li>\n<strong>Pallu:</strong> Ajrak Print with Lakdi Patta Design</li>\n<li>\n<strong>Border:</strong> Same Tone Piping Border with Weaving Border</li>\n<li>\n<strong>Blouse:</strong> Matching Ajrak Print Blouse Fabric with Weaving Border (Unstitched)</li>\n</ul>\n<h4>Blouse Note</h4>\n<p><em>The model is wearing a stitched blouse for styling purposes. The saree comes with an unstitched blouse piece in matching Ajrak print fabric with weaving border.</em></p>\n<h4>Color</h4>\n<p><strong>Kumkum Maroon</strong></p>\n<h4>Why You'll Love It</h4>\n<p>The rich maroon tone, traditional Ajrak artistry, subtle mirror accents, and luxurious modal satin silk drape make this saree a perfect choice for festive gatherings, family functions, poojas, and celebrations.<br><br><br></p>\n<br>\n</li>\n</ul>",
    "salePrice": 5450,
    "regularPrice": 5450,
    "category": "Silk",
    "status": "Available",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC2423.jpg?v=1781778496",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC2423.jpg?v=1781778496",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC2395.jpg?v=1781778492",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC2419.jpg?v=1781778492",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC2377.jpg?v=1781778495",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC2432.jpg?v=1781778492",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC2471.jpg?v=1781778561"
    ],
    "tags": [
      "Ajrak Print Saree",
      "Designer Saree",
      "Festive Wear Saree",
      "Kumkum Maroon Saree",
      "Lakdi Patta Pallu Saree",
      "Mirror Work Saree",
      "Modal Silk Saree",
      "Party Wear Saree",
      "ShopHub",
      "Pure Modal Satin Silk Saree",
      "Traditional Saree",
      "Weaving Border Saree"
    ],
    "featured": true,
    "bestSeller": true,
    "newArrival": false,
    "rating": 5,
    "reviewCount": 4,
    "createdAt": "2026-06-25T07:55:30.164Z"
  },
  {
    "title": "Lavender Mist – Printed Chinon Saree with Hand Tube & Diamond Work",
    "slug": "lavender-mist-printed-chinon-saree-with-hand-tube-diamond-work",
    "description": "Graceful, dreamy, and effortlessly elegant, our Lavender Mist Printed Chinon Saree is designed for women who love understated sophistication. Crafted from soft and flowy Chinon fabric, this saree features a beautiful ombre lavender shade , highlighted with delicate leaf prints , intricate hand tube work , and subtle diamond embellishments that add a touch of sparkle. The lightweight drape, soft texture, and refined detailing make it perfect for brunches, parties, festive gatherings, and special ",
    "fullDescription": "<p>Graceful, dreamy, and effortlessly elegant, our <strong>Lavender Mist Printed Chinon Saree</strong> is designed for women who love understated sophistication. Crafted from soft and flowy Chinon fabric, this saree features a beautiful <strong>ombre lavender shade</strong>, highlighted with delicate <strong>leaf prints</strong>, intricate <strong>hand tube work</strong>, and subtle <strong>diamond embellishments</strong> that add a touch of sparkle.</p>\n<p>The lightweight drape, soft texture, and refined detailing make it perfect for brunches, parties, festive gatherings, and special occasions. Paired with a matching printed Chinon blouse fabric, this ensemble offers both comfort and style.</p>\n<p>A timeless saree that blends contemporary charm with feminine elegance.</p>\n<h4>Product Highlights</h4>\n<ul>\n<li>Premium Chinon Fabric</li>\n<li>Elegant Ombre Lavender Shade</li>\n<li>Delicate Leaf Print Design</li>\n<li>Hand Tube Work Detailing</li>\n<li>Diamond Embellishments</li>\n<li>Lightweight &amp; Flowing Drape</li>\n<li>Soft Scalloped Border Finish</li>\n<li>Matching Printed Chinon Blouse Included</li>\n<li>Perfect for Parties, Festive Wear &amp; Special Occasions<br><br><meta charset=\"UTF-8\">\n<h4>Fabric Details</h4>\n<ul>\n<li>\n<strong>Saree Fabric:</strong> Chinon</li>\n<li>\n<strong>Work:</strong> Hand Tube Work &amp; Diamond Work</li>\n<li>\n<strong>Design:</strong> Printed Leaf Motifs</li>\n<li>\n<strong>Blouse Fabric:</strong> Matching Printed Chinon Blouse Piece (Unstitched)</li>\n</ul>\n<h4>Blouse Note</h4>\n<p><em>The model is wearing a stitched blouse for styling purposes. The saree comes with an unstitched blouse piece in matching fabric and design.</em></p>\n<h4>Color</h4>\n<p><strong>Lavender Mist</strong></p>\n<br>\n</li>\n</ul>",
    "salePrice": 1849,
    "regularPrice": 1849,
    "category": "Silk",
    "status": "Available",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC2467.jpg?v=1782019482",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC2467.jpg?v=1782019482",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC2460.jpg?v=1782019466",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC2463.jpg?v=1782019504",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC2465.jpg?v=1782019456",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC2466.jpg?v=1782019491",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC2320.jpg?v=1781702610"
    ],
    "tags": [
      "Chinon Saree",
      "Designer Saree",
      "Diamond Work Saree",
      "Elegant Saree",
      "Festive Wear Saree",
      "Hand Tube Work Saree",
      "Lavender Saree",
      "Lightweight Saree",
      "Ombre Saree",
      "Party Wear Saree",
      "ShopHub",
      "Printed Saree"
    ],
    "featured": true,
    "bestSeller": true,
    "newArrival": false,
    "rating": 4,
    "reviewCount": 5,
    "createdAt": "2026-06-25T07:55:30.164Z"
  },
  {
    "title": "Premium Satin Organza Saree with Diamond Work Border",
    "slug": "premium-satin-organza-saree-with-diamond-work-border",
    "description": "Step into elegance with this beautifully crafted Satin Organza saree designed in soothing pastel pink shades with graceful contrast accents. The saree features a soft glossy finish and lightweight flow that creates a dreamy and sophisticated look. Enhanced with delicate diamond work borders and subtle shimmering detailing across the drape, this saree perfectly blends modern charm with timeless elegance. The airy organza texture paired with satin richness gives it a luxurious fall and effortless ",
    "fullDescription": "<p data-end=\"347\" data-start=\"100\">Step into elegance with this beautifully crafted Satin Organza saree designed in soothing pastel pink shades with graceful contrast accents. The saree features a soft glossy finish and lightweight flow that creates a dreamy and sophisticated look.</p>\n<p data-end=\"607\" data-start=\"349\">Enhanced with delicate diamond work borders and subtle shimmering detailing across the drape, this saree perfectly blends modern charm with timeless elegance. The airy organza texture paired with satin richness gives it a luxurious fall and effortless grace.</p>\n<p data-end=\"711\" data-start=\"609\">An ideal pick for receptions, parties, festive occasions, bridesmaids, and elegant evening gatherings.</p>\n<h3 data-end=\"729\" data-start=\"713\" data-section-id=\"1au80px\">Highlights</h3>\n<ul data-end=\"946\" data-start=\"730\">\n<li data-end=\"762\" data-start=\"730\" data-section-id=\"14gmy8x\">Premium Satin Organza Fabric</li>\n<li data-end=\"794\" data-start=\"763\" data-section-id=\"qysekx\">Elegant Diamond Work Border</li>\n<li data-end=\"821\" data-start=\"795\" data-section-id=\"15oow9m\">Soft Lightweight Drape</li>\n<li data-end=\"845\" data-start=\"822\" data-section-id=\"3rtfdz\">Glossy Satin Finish</li>\n<li data-end=\"874\" data-start=\"846\" data-section-id=\"9mxa05\">Subtle Shimmer Detailing</li>\n<li data-end=\"909\" data-start=\"875\" data-section-id=\"5u09jb\">Stylish Pastel Contrast Design</li>\n<li data-end=\"946\" data-start=\"910\" data-section-id=\"rs5s2f\">Perfect for Party &amp; Festive Wear<br><br>\n<p data-end=\"1083\" data-start=\"1043\"><strong data-end=\"1068\" data-start=\"1043\"><span>NOTE : The blouse worn by the model might be for modelling purpose only. Check the image of the blouse piece to understand how the actual blouse piece looks like</span></strong></p>\n<p data-end=\"1083\" data-start=\"1043\"> </p>\n<br>\n</li>\n</ul>",
    "salePrice": 2650,
    "regularPrice": 3899,
    "category": "Silk",
    "status": "Available",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1663.jpg?v=1780832654",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1663.jpg?v=1780832654",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1646.jpg?v=1780832654",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1715.jpg?v=1780832654",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1772.jpg?v=1780832656"
    ],
    "tags": [
      "#DesignerSaree",
      "#DiamondWorkSaree",
      "#ElegantSaree",
      "#FestiveWear",
      "#LuxuryEthnicWear",
      "#OrganzaLove",
      "#PartyWearSaree",
      "#PastelSaree",
      "#PinkSaree",
      "#shophub",
      "#SatinOrganzaSaree",
      "#WeddingCollection"
    ],
    "featured": true,
    "bestSeller": true,
    "newArrival": false,
    "rating": 5,
    "reviewCount": 6,
    "createdAt": "2026-06-25T07:55:30.164Z"
  },
  {
    "title": "Vintage Semi Gadwal Pattu Saree with Kanchi Border-MAROON",
    "slug": "vintage-semi-gadwal-pattu-saree-with-kanchi-border-coffee-brown",
    "description": "Step into timeless tradition with our elegant Vintage Semi Gadwal Pattu Sarees beautifully crafted with rich Kanchi style borders. Featuring an exquisite 10-inch grand zari woven border, these sarees reflect the beauty of classic South Indian heritage with a luxurious vintage touch. Designed with intricate traditional motifs and fine zari detailing across the body, these sarees offer a rich festive appearance while remaining lightweight and comfortable to wear. The contrast borders and vibrant c",
    "fullDescription": "<p data-start=\"72\" data-end=\"383\">Step into timeless tradition with our elegant <em data-start=\"144\" data-end=\"178\">Vintage Semi Gadwal Pattu Sarees</em> beautifully crafted with rich Kanchi style borders. Featuring an exquisite 10-inch grand zari woven border, these sarees reflect the beauty of classic South Indian heritage with a luxurious vintage touch.</p>\n<p data-start=\"385\" data-end=\"735\">Designed with intricate traditional motifs and fine zari detailing across the body, these sarees offer a rich festive appearance while remaining lightweight and comfortable to wear. The contrast borders and vibrant color combinations make them a perfect choice for weddings, festive celebrations, poojas, family gatherings, and traditional occasions.</p>\n<p data-start=\"737\" data-end=\"803\">Available in 5 stunning colors to suit every mood and celebration.</p>\n<p data-start=\"805\" data-end=\"1085\"><strong data-start=\"805\" data-end=\"819\">Highlights</strong><br data-start=\"819\" data-end=\"822\">• Vintage Semi Gadwal Pattu Saree<br data-start=\"855\" data-end=\"858\">• Rich 10-Inch Kanchi Zari Border<br data-start=\"891\" data-end=\"894\">• Elegant Traditional Motifs<br data-start=\"922\" data-end=\"925\">• Lightweight &amp; Comfortable Drape<br data-start=\"958\" data-end=\"961\">• Grand Festive Look<br data-start=\"981\" data-end=\"984\">• Soft Silk Feel Finish<br data-start=\"1007\" data-end=\"1010\">• Available in 5 Beautiful Colors<br data-start=\"1043\" data-end=\"1046\">• Perfect for Weddings &amp; Festive Wear</p>",
    "salePrice": 3800,
    "regularPrice": 3800,
    "category": "Silk",
    "status": "Available",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1444_8525c311-0fb4-46c9-8b92-b55daeb03b50.jpg?v=1780205620",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1444_8525c311-0fb4-46c9-8b92-b55daeb03b50.jpg?v=1780205620"
    ],
    "tags": [
      "#SemiGadwal #VintageSaree #KanchiBorder #TraditionalSaree #PattuSaree #SouthIndianStyle #ZariWeaving #FestiveWear #WeddingSaree #EthnicElegance #ClassicWeaves #shophub"
    ],
    "featured": true,
    "bestSeller": false,
    "newArrival": true,
    "rating": 4,
    "reviewCount": 7,
    "createdAt": "2026-06-25T07:55:30.164Z"
  },
  {
    "title": "Vintage Semi Gadwal Pattu Saree with Kanchi Border-PINK",
    "slug": "vintage-semi-gadwal-pattu-saree-with-kanchi-border-pink-1",
    "description": "Step into timeless tradition with our elegant Vintage Semi Gadwal Pattu Sarees beautifully crafted with rich Kanchi style borders. Featuring an exquisite 10-inch grand zari woven border, these sarees reflect the beauty of classic South Indian heritage with a luxurious vintage touch. Designed with intricate traditional motifs and fine zari detailing across the body, these sarees offer a rich festive appearance while remaining lightweight and comfortable to wear. The contrast borders and vibrant c",
    "fullDescription": "<p data-start=\"72\" data-end=\"383\">Step into timeless tradition with our elegant <em data-start=\"144\" data-end=\"178\">Vintage Semi Gadwal Pattu Sarees</em> beautifully crafted with rich Kanchi style borders. Featuring an exquisite 10-inch grand zari woven border, these sarees reflect the beauty of classic South Indian heritage with a luxurious vintage touch.</p>\n<p data-start=\"385\" data-end=\"735\">Designed with intricate traditional motifs and fine zari detailing across the body, these sarees offer a rich festive appearance while remaining lightweight and comfortable to wear. The contrast borders and vibrant color combinations make them a perfect choice for weddings, festive celebrations, poojas, family gatherings, and traditional occasions.</p>\n<p data-start=\"737\" data-end=\"803\">Available in 5 stunning colors to suit every mood and celebration.</p>\n<p data-start=\"805\" data-end=\"1085\"><strong data-start=\"805\" data-end=\"819\">Highlights</strong><br data-start=\"819\" data-end=\"822\">• Vintage Semi Gadwal Pattu Saree<br data-start=\"855\" data-end=\"858\">• Rich 10-Inch Kanchi Zari Border<br data-start=\"891\" data-end=\"894\">• Elegant Traditional Motifs<br data-start=\"922\" data-end=\"925\">• Lightweight &amp; Comfortable Drape<br data-start=\"958\" data-end=\"961\">• Grand Festive Look<br data-start=\"981\" data-end=\"984\">• Soft Silk Feel Finish<br data-start=\"1007\" data-end=\"1010\">• Available in 5 Beautiful Colors<br data-start=\"1043\" data-end=\"1046\">• Perfect for Weddings &amp; Festive Wear</p>",
    "salePrice": 3800,
    "regularPrice": 3800,
    "category": "Silk",
    "status": "Available",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1445_4dcc9408-39c5-4800-9ccd-208cc6c9c039.jpg?v=1780204671",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1445_4dcc9408-39c5-4800-9ccd-208cc6c9c039.jpg?v=1780204671"
    ],
    "tags": [
      "#SemiGadwal #VintageSaree #KanchiBorder #TraditionalSaree #PattuSaree #SouthIndianStyle #ZariWeaving #FestiveWear #WeddingSaree #EthnicElegance #ClassicWeaves #shophub"
    ],
    "featured": true,
    "bestSeller": false,
    "newArrival": true,
    "rating": 5,
    "reviewCount": 8,
    "createdAt": "2026-06-25T07:55:30.164Z"
  },
  {
    "title": "Moon Mist – Printed Chinon Designer Saree",
    "slug": "moon-mist-printed-chinon-designer-saree",
    "description": "Graceful, lightweight, and effortlessly elegant, Moon Mist is a beautifully crafted Printed Chinon Saree designed for women who love subtle sophistication. Featuring delicate leaf-inspired prints across a soothing dual-tone blue palette, this saree is enhanced with intricate hand tube and diamond work along the border, adding just the right touch of sparkle. The soft and flowy Chinon fabric creates a beautiful drape, making it perfect for parties, office events, casual celebrations, brunch outin",
    "fullDescription": "<p data-start=\"63\" data-end=\"451\">Graceful, lightweight, and effortlessly elegant, <em data-start=\"138\" data-end=\"149\">Moon Mist</em> is a beautifully crafted Printed Chinon Saree designed for women who love subtle sophistication. Featuring delicate leaf-inspired prints across a soothing dual-tone blue palette, this saree is enhanced with intricate hand tube and diamond work along the border, adding just the right touch of sparkle.</p>\n<p data-start=\"453\" data-end=\"751\">The soft and flowy Chinon fabric creates a beautiful drape, making it perfect for parties, office events, casual celebrations, brunch outings, and evening gatherings. Paired with a matching printed blouse in the same fabric, this ensemble offers a refined and contemporary look with timeless charm.</p>\n<p data-start=\"753\" data-end=\"814\">A perfect blend of comfort, elegance, and understated luxury.</p>\n<p data-start=\"816\" data-end=\"1135\"><strong data-start=\"816\" data-end=\"830\">Highlights</strong><br data-start=\"830\" data-end=\"833\">• Premium Printed Chinon Fabric<br data-start=\"864\" data-end=\"867\">• Elegant Hand Tube &amp; Diamond Work Border<br data-start=\"908\" data-end=\"911\">• Beautiful Leaf Print Design<br data-start=\"940\" data-end=\"943\">• Lightweight &amp; Flowy Drape<br data-start=\"970\" data-end=\"973\">• Soft, Comfortable Feel<br data-start=\"997\" data-end=\"1000\" data-is-only-node=\"\">• Matching Printed Chinon Blouse Included<br data-start=\"1041\" data-end=\"1044\">• Perfect for Parties, Office Wear &amp; Special Occasions<br data-start=\"1098\" data-end=\"1101\">• Contemporary Designer Collection</p>\n<p data-start=\"1137\" data-end=\"1174\"><strong>NOTE: The model is wearing the stitched version of the blouse included with the saree. The actual blouse piece comes unstitched.</strong></p>",
    "salePrice": 1849,
    "regularPrice": 1849,
    "category": "Designer",
    "status": "Available",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1594.jpg?v=1780057073",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1594.jpg?v=1780057073",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1450.jpg?v=1780057073",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1532.jpg?v=1780057076",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1511.jpg?v=1780057073",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1613.jpg?v=1780057073"
    ],
    "tags": [],
    "featured": true,
    "bestSeller": false,
    "newArrival": true,
    "rating": 4,
    "reviewCount": 9,
    "createdAt": "2026-06-25T07:55:30.164Z"
  },
  {
    "title": "Vintage Semi Gadwal Pattu Saree with Kanchi Border-BLUE RED",
    "slug": "vintage-semi-gadwal-pattu-saree-with-kanchi-border-pink",
    "description": "Step into timeless tradition with our elegant Vintage Semi Gadwal Pattu Sarees beautifully crafted with rich Kanchi style borders. Featuring an exquisite 10-inch grand zari woven border, these sarees reflect the beauty of classic South Indian heritage with a luxurious vintage touch. Designed with intricate traditional motifs and fine zari detailing across the body, these sarees offer a rich festive appearance while remaining lightweight and comfortable to wear. The contrast borders and vibrant c",
    "fullDescription": "<p data-start=\"72\" data-end=\"383\">Step into timeless tradition with our elegant <em data-start=\"144\" data-end=\"178\">Vintage Semi Gadwal Pattu Sarees</em> beautifully crafted with rich Kanchi style borders. Featuring an exquisite 10-inch grand zari woven border, these sarees reflect the beauty of classic South Indian heritage with a luxurious vintage touch.</p>\n<p data-start=\"385\" data-end=\"735\">Designed with intricate traditional motifs and fine zari detailing across the body, these sarees offer a rich festive appearance while remaining lightweight and comfortable to wear. The contrast borders and vibrant color combinations make them a perfect choice for weddings, festive celebrations, poojas, family gatherings, and traditional occasions.</p>\n<p data-start=\"737\" data-end=\"803\">Available in 5 stunning colors to suit every mood and celebration.</p>\n<p data-start=\"805\" data-end=\"1085\"><strong data-start=\"805\" data-end=\"819\">Highlights</strong><br data-start=\"819\" data-end=\"822\">• Vintage Semi Gadwal Pattu Saree<br data-start=\"855\" data-end=\"858\">• Rich 10-Inch Kanchi Zari Border<br data-start=\"891\" data-end=\"894\">• Elegant Traditional Motifs<br data-start=\"922\" data-end=\"925\">• Lightweight &amp; Comfortable Drape<br data-start=\"958\" data-end=\"961\">• Grand Festive Look<br data-start=\"981\" data-end=\"984\">• Soft Silk Feel Finish<br data-start=\"1007\" data-end=\"1010\">• Available in 5 Beautiful Colors<br data-start=\"1043\" data-end=\"1046\">• Perfect for Weddings &amp; Festive Wear</p>",
    "salePrice": 3999,
    "regularPrice": 3999,
    "category": "Silk",
    "status": "Sold out",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1434_d98c7a69-c5a6-4fc7-ba87-99ce8789e4e9.jpg?v=1779982202",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1434_d98c7a69-c5a6-4fc7-ba87-99ce8789e4e9.jpg?v=1779982202"
    ],
    "tags": [
      "#SemiGadwal #VintageSaree #KanchiBorder #TraditionalSaree #PattuSaree #SouthIndianStyle #ZariWeaving #FestiveWear #WeddingSaree #EthnicElegance #ClassicWeaves #shophub"
    ],
    "featured": true,
    "bestSeller": false,
    "newArrival": true,
    "rating": 5,
    "reviewCount": 10,
    "createdAt": "2026-06-25T07:55:30.164Z"
  },
  {
    "title": "Classic Semi Gadwal Saree Collection- MAGANTA",
    "slug": "classic-semi-gadwal-saree-collection-maganta",
    "description": "Celebrate timeless South Indian elegance with our beautifully crafted Semi Gadwal Sarees . Designed with rich traditional charm, these sarees feature elegant zari woven borders, classic motifs, and graceful color combinations that never go out of style. Lightweight, comfortable, and easy to drape, these sarees are perfect for festivals, poojas, office wear, family gatherings, and traditional occasions. The subtle zari detailing and refined finish add a rich ethnic appeal while maintaining everyd",
    "fullDescription": "<p data-start=\"58\" data-end=\"338\">Celebrate timeless South Indian elegance with our beautifully crafted <em data-start=\"154\" data-end=\"174\">Semi Gadwal Sarees</em>. Designed with rich traditional charm, these sarees feature elegant zari woven borders, classic motifs, and graceful color combinations that never go out of style.</p>\n<p data-start=\"340\" data-end=\"597\">Lightweight, comfortable, and easy to drape, these sarees are perfect for festivals, poojas, office wear, family gatherings, and traditional occasions. The subtle zari detailing and refined finish add a rich ethnic appeal while maintaining everyday comfort.</p>\n<p data-start=\"599\" data-end=\"681\">Available in elegant shades that reflect heritage, simplicity, and sophistication.</p>\n<p data-start=\"683\" data-end=\"926\"><strong data-start=\"683\" data-end=\"697\">Highlights</strong><br data-start=\"697\" data-end=\"700\">• Semi Gadwal Traditional Saree<br data-start=\"731\" data-end=\"734\">• Elegant Zari Woven Border<br data-start=\"761\" data-end=\"764\">• Lightweight &amp; Comfortable Fabric<br data-start=\"798\" data-end=\"801\">• Rich Traditional Look<br data-start=\"824\" data-end=\"827\">• Soft &amp; Easy Drape<br data-start=\"846\" data-end=\"849\">• Perfect for Festivals &amp; Daily Ethnic Wear<br data-start=\"892\" data-end=\"895\">• Classic South Indian Design</p>\n<p data-start=\"928\" data-end=\"971\"> </p>",
    "salePrice": 2999,
    "regularPrice": 2999,
    "category": "Silk",
    "status": "Available",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1995.jpg?v=1781005892",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1995.jpg?v=1781005892",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1988.jpg?v=1781005892",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC2042.jpg?v=1781005894",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1430_cc5748c3-6e1a-4c13-9a53-ba5e0c5d46f6.jpg?v=1779980527",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1432_026ff64e-b289-42f4-8b63-67c5155e3646.jpg?v=1781006260"
    ],
    "tags": [
      "#SemiGadwal #GadwalSaree #TraditionalSaree #EthnicWear #SouthIndianStyle #ZariBorderSaree #FestiveWear #ClassicSaree #ElegantDrape #DailyWearSaree #shophub"
    ],
    "featured": false,
    "bestSeller": false,
    "newArrival": true,
    "rating": 4,
    "reviewCount": 3,
    "createdAt": "2026-06-25T07:55:30.164Z"
  },
  {
    "title": "Classic Semi Gadwal Saree Collection- BLACK",
    "slug": "classic-semi-gadwal-saree-collection-black",
    "description": "Celebrate timeless South Indian elegance with our beautifully crafted Semi Gadwal Sarees . Designed with rich traditional charm, these sarees feature elegant zari woven borders, classic motifs, and graceful color combinations that never go out of style. Lightweight, comfortable, and easy to drape, these sarees are perfect for festivals, poojas, office wear, family gatherings, and traditional occasions. The subtle zari detailing and refined finish add a rich ethnic appeal while maintaining everyd",
    "fullDescription": "<p data-start=\"58\" data-end=\"338\">Celebrate timeless South Indian elegance with our beautifully crafted <em data-start=\"154\" data-end=\"174\">Semi Gadwal Sarees</em>. Designed with rich traditional charm, these sarees feature elegant zari woven borders, classic motifs, and graceful color combinations that never go out of style.</p>\n<p data-start=\"340\" data-end=\"597\">Lightweight, comfortable, and easy to drape, these sarees are perfect for festivals, poojas, office wear, family gatherings, and traditional occasions. The subtle zari detailing and refined finish add a rich ethnic appeal while maintaining everyday comfort.</p>\n<p data-start=\"599\" data-end=\"681\">Available in elegant shades that reflect heritage, simplicity, and sophistication.</p>\n<p data-start=\"683\" data-end=\"926\"><strong data-start=\"683\" data-end=\"697\">Highlights</strong><br data-start=\"697\" data-end=\"700\">• Semi Gadwal Traditional Saree<br data-start=\"731\" data-end=\"734\">• Elegant Zari Woven Border<br data-start=\"761\" data-end=\"764\">• Lightweight &amp; Comfortable Fabric<br data-start=\"798\" data-end=\"801\">• Rich Traditional Look<br data-start=\"824\" data-end=\"827\">• Soft &amp; Easy Drape<br data-start=\"846\" data-end=\"849\">• Perfect for Festivals &amp; Daily Ethnic Wear<br data-start=\"892\" data-end=\"895\">• Classic South Indian Design</p>\n<p data-start=\"928\" data-end=\"971\"> </p>",
    "salePrice": 2999,
    "regularPrice": 2999,
    "category": "Silk",
    "status": "Sold out",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1431_ced4259d-2ab2-4421-9587-f46301f07207.jpg?v=1779980697",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1431_ced4259d-2ab2-4421-9587-f46301f07207.jpg?v=1779980697"
    ],
    "tags": [
      "#SemiGadwal #GadwalSaree #TraditionalSaree #EthnicWear #SouthIndianStyle #ZariBorderSaree #FestiveWear #ClassicSaree #ElegantDrape #DailyWearSaree #shophub"
    ],
    "featured": false,
    "bestSeller": false,
    "newArrival": true,
    "rating": 5,
    "reviewCount": 4,
    "createdAt": "2026-06-25T07:55:30.164Z"
  },
  {
    "title": "Classic Semi Gadwal Saree Collection- BLUE",
    "slug": "classic-semi-gadwal-saree-collection-blue",
    "description": "Celebrate timeless South Indian elegance with our beautifully crafted Semi Gadwal Sarees . Designed with rich traditional charm, these sarees feature elegant zari woven borders, classic motifs, and graceful color combinations that never go out of style. Lightweight, comfortable, and easy to drape, these sarees are perfect for festivals, poojas, office wear, family gatherings, and traditional occasions. The subtle zari detailing and refined finish add a rich ethnic appeal while maintaining everyd",
    "fullDescription": "<p data-start=\"58\" data-end=\"338\">Celebrate timeless South Indian elegance with our beautifully crafted <em data-start=\"154\" data-end=\"174\">Semi Gadwal Sarees</em>. Designed with rich traditional charm, these sarees feature elegant zari woven borders, classic motifs, and graceful color combinations that never go out of style.</p>\n<p data-start=\"340\" data-end=\"597\">Lightweight, comfortable, and easy to drape, these sarees are perfect for festivals, poojas, office wear, family gatherings, and traditional occasions. The subtle zari detailing and refined finish add a rich ethnic appeal while maintaining everyday comfort.</p>\n<p data-start=\"599\" data-end=\"681\">Available in elegant shades that reflect heritage, simplicity, and sophistication.</p>\n<p data-start=\"683\" data-end=\"926\"><strong data-start=\"683\" data-end=\"697\">Highlights</strong><br data-start=\"697\" data-end=\"700\">• Semi Gadwal Traditional Saree<br data-start=\"731\" data-end=\"734\">• Elegant Zari Woven Border<br data-start=\"761\" data-end=\"764\">• Lightweight &amp; Comfortable Fabric<br data-start=\"798\" data-end=\"801\">• Rich Traditional Look<br data-start=\"824\" data-end=\"827\">• Soft &amp; Easy Drape<br data-start=\"846\" data-end=\"849\">• Perfect for Festivals &amp; Daily Ethnic Wear<br data-start=\"892\" data-end=\"895\">• Classic South Indian Design</p>\n<p data-start=\"928\" data-end=\"971\"> </p>",
    "salePrice": 2999,
    "regularPrice": 2999,
    "category": "Silk",
    "status": "Sold out",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1433_852970e9-f373-4d84-82ba-d6bda61e2492.jpg?v=1779980795",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1433_852970e9-f373-4d84-82ba-d6bda61e2492.jpg?v=1779980795"
    ],
    "tags": [
      "#SemiGadwal #GadwalSaree #TraditionalSaree #EthnicWear #SouthIndianStyle #ZariBorderSaree #FestiveWear #ClassicSaree #ElegantDrape #DailyWearSaree #shophub"
    ],
    "featured": false,
    "bestSeller": false,
    "newArrival": true,
    "rating": 4,
    "reviewCount": 5,
    "createdAt": "2026-06-25T07:55:30.164Z"
  },
  {
    "title": "Vintage Semi Gadwal Pattu Saree with Kanchi Border-RED",
    "slug": "vintage-semi-gadwal-pattu-saree-with-kanchi-border-red",
    "description": "Step into timeless tradition with our elegant Vintage Semi Gadwal Pattu Sarees beautifully crafted with rich Kanchi style borders. Featuring an exquisite 10-inch grand zari woven border, these sarees reflect the beauty of classic South Indian heritage with a luxurious vintage touch. Designed with intricate traditional motifs and fine zari detailing across the body, these sarees offer a rich festive appearance while remaining lightweight and comfortable to wear. The contrast borders and vibrant c",
    "fullDescription": "<p data-start=\"72\" data-end=\"383\">Step into timeless tradition with our elegant <em data-start=\"144\" data-end=\"178\">Vintage Semi Gadwal Pattu Sarees</em> beautifully crafted with rich Kanchi style borders. Featuring an exquisite 10-inch grand zari woven border, these sarees reflect the beauty of classic South Indian heritage with a luxurious vintage touch.</p>\n<p data-start=\"385\" data-end=\"735\">Designed with intricate traditional motifs and fine zari detailing across the body, these sarees offer a rich festive appearance while remaining lightweight and comfortable to wear. The contrast borders and vibrant color combinations make them a perfect choice for weddings, festive celebrations, poojas, family gatherings, and traditional occasions.</p>\n<p data-start=\"737\" data-end=\"803\">Available in 5 stunning colors to suit every mood and celebration.</p>\n<p data-start=\"805\" data-end=\"1085\"><strong data-start=\"805\" data-end=\"819\">Highlights</strong><br data-start=\"819\" data-end=\"822\">• Vintage Semi Gadwal Pattu Saree<br data-start=\"855\" data-end=\"858\">• Rich 10-Inch Kanchi Zari Border<br data-start=\"891\" data-end=\"894\">• Elegant Traditional Motifs<br data-start=\"922\" data-end=\"925\">• Lightweight &amp; Comfortable Drape<br data-start=\"958\" data-end=\"961\">• Grand Festive Look<br data-start=\"981\" data-end=\"984\">• Soft Silk Feel Finish<br data-start=\"1007\" data-end=\"1010\">• Available in 5 Beautiful Colors<br data-start=\"1043\" data-end=\"1046\">• Perfect for Weddings &amp; Festive Wear</p>",
    "salePrice": 3800,
    "regularPrice": 3800,
    "category": "Silk",
    "status": "Sold out",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1445_3b28e73a-ced9-4ae0-8fc4-ea82c39ea68c.jpg?v=1779981636",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1445_3b28e73a-ced9-4ae0-8fc4-ea82c39ea68c.jpg?v=1779981636"
    ],
    "tags": [
      "#SemiGadwal #VintageSaree #KanchiBorder #TraditionalSaree #PattuSaree #SouthIndianStyle #ZariWeaving #FestiveWear #WeddingSaree #EthnicElegance #ClassicWeaves #shophub"
    ],
    "featured": false,
    "bestSeller": false,
    "newArrival": true,
    "rating": 5,
    "reviewCount": 6,
    "createdAt": "2026-06-25T07:55:30.164Z"
  },
  {
    "title": "Vintage Semi Gadwal Pattu Saree with Kanchi Border-BROWN",
    "slug": "vintage-semi-gadwal-pattu-saree-with-kanchi-border-brown",
    "description": "Step into timeless tradition with our elegant Vintage Semi Gadwal Pattu Sarees beautifully crafted with rich Kanchi style borders. Featuring an exquisite 10-inch grand zari woven border, these sarees reflect the beauty of classic South Indian heritage with a luxurious vintage touch. Designed with intricate traditional motifs and fine zari detailing across the body, these sarees offer a rich festive appearance while remaining lightweight and comfortable to wear. The contrast borders and vibrant c",
    "fullDescription": "<p data-start=\"72\" data-end=\"383\">Step into timeless tradition with our elegant <em data-start=\"144\" data-end=\"178\">Vintage Semi Gadwal Pattu Sarees</em> beautifully crafted with rich Kanchi style borders. Featuring an exquisite 10-inch grand zari woven border, these sarees reflect the beauty of classic South Indian heritage with a luxurious vintage touch.</p>\n<p data-start=\"385\" data-end=\"735\">Designed with intricate traditional motifs and fine zari detailing across the body, these sarees offer a rich festive appearance while remaining lightweight and comfortable to wear. The contrast borders and vibrant color combinations make them a perfect choice for weddings, festive celebrations, poojas, family gatherings, and traditional occasions.</p>\n<p data-start=\"737\" data-end=\"803\">Available in 5 stunning colors to suit every mood and celebration.</p>\n<p data-start=\"805\" data-end=\"1085\"><strong data-start=\"805\" data-end=\"819\">Highlights</strong><br data-start=\"819\" data-end=\"822\">• Vintage Semi Gadwal Pattu Saree<br data-start=\"855\" data-end=\"858\">• Rich 10-Inch Kanchi Zari Border<br data-start=\"891\" data-end=\"894\">• Elegant Traditional Motifs<br data-start=\"922\" data-end=\"925\">• Lightweight &amp; Comfortable Drape<br data-start=\"958\" data-end=\"961\">• Grand Festive Look<br data-start=\"981\" data-end=\"984\">• Soft Silk Feel Finish<br data-start=\"1007\" data-end=\"1010\">• Available in 5 Beautiful Colors<br data-start=\"1043\" data-end=\"1046\">• Perfect for Weddings &amp; Festive Wear</p>",
    "salePrice": 3800,
    "regularPrice": 3800,
    "category": "Silk",
    "status": "Sold out",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1443_e2b36470-4d30-4da5-8701-8a177ce4d35d.jpg?v=1779981536",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1443_e2b36470-4d30-4da5-8701-8a177ce4d35d.jpg?v=1779981536"
    ],
    "tags": [
      "#SemiGadwal #VintageSaree #KanchiBorder #TraditionalSaree #PattuSaree #SouthIndianStyle #ZariWeaving #FestiveWear #WeddingSaree #EthnicElegance #ClassicWeaves #shophub"
    ],
    "featured": false,
    "bestSeller": false,
    "newArrival": false,
    "rating": 4,
    "reviewCount": 7,
    "createdAt": "2026-06-25T07:55:30.165Z"
  },
  {
    "title": "Vintage Semi Gadwal Pattu Saree with Kanchi Border- BLACK",
    "slug": "vintage-semi-gadwal-pattu-saree-with-kanchi-border-black",
    "description": "Step into timeless tradition with our elegant Vintage Semi Gadwal Pattu Sarees beautifully crafted with rich Kanchi style borders. Featuring an exquisite 10-inch grand zari woven border, these sarees reflect the beauty of classic South Indian heritage with a luxurious vintage touch. Designed with intricate traditional motifs and fine zari detailing across the body, these sarees offer a rich festive appearance while remaining lightweight and comfortable to wear. The contrast borders and vibrant c",
    "fullDescription": "<p data-start=\"72\" data-end=\"383\">Step into timeless tradition with our elegant <em data-start=\"144\" data-end=\"178\">Vintage Semi Gadwal Pattu Sarees</em> beautifully crafted with rich Kanchi style borders. Featuring an exquisite 10-inch grand zari woven border, these sarees reflect the beauty of classic South Indian heritage with a luxurious vintage touch.</p>\n<p data-start=\"385\" data-end=\"735\">Designed with intricate traditional motifs and fine zari detailing across the body, these sarees offer a rich festive appearance while remaining lightweight and comfortable to wear. The contrast borders and vibrant color combinations make them a perfect choice for weddings, festive celebrations, poojas, family gatherings, and traditional occasions.</p>\n<p data-start=\"737\" data-end=\"803\">Available in 5 stunning colors to suit every mood and celebration.</p>\n<p data-start=\"805\" data-end=\"1085\"><strong data-start=\"805\" data-end=\"819\">Highlights</strong><br data-start=\"819\" data-end=\"822\">• Vintage Semi Gadwal Pattu Saree<br data-start=\"855\" data-end=\"858\">• Rich 10-Inch Kanchi Zari Border<br data-start=\"891\" data-end=\"894\">• Elegant Traditional Motifs<br data-start=\"922\" data-end=\"925\">• Lightweight &amp; Comfortable Drape<br data-start=\"958\" data-end=\"961\">• Grand Festive Look<br data-start=\"981\" data-end=\"984\">• Soft Silk Feel Finish<br data-start=\"1007\" data-end=\"1010\">• Available in 5 Beautiful Colors<br data-start=\"1043\" data-end=\"1046\">• Perfect for Weddings &amp; Festive Wear</p>",
    "salePrice": 3800,
    "regularPrice": 3800,
    "category": "Silk",
    "status": "Sold out",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1408.jpg?v=1779981151",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1408.jpg?v=1779981151"
    ],
    "tags": [
      "#SemiGadwal #VintageSaree #KanchiBorder #TraditionalSaree #PattuSaree #SouthIndianStyle #ZariWeaving #FestiveWear #WeddingSaree #EthnicElegance #ClassicWeaves #shophub"
    ],
    "featured": false,
    "bestSeller": false,
    "newArrival": false,
    "rating": 5,
    "reviewCount": 8,
    "createdAt": "2026-06-25T07:55:30.165Z"
  },
  {
    "title": "Ivory Grace – Linen Shimmer Saree",
    "slug": "ivory-grace-linen-shimmer-saree",
    "description": "Bring home understated elegance with Ivory Grace , a beautifully crafted linen shimmer saree designed for timeless festive styling. Featuring a soft ivory tone with elegant zari weaving borders, this saree is enhanced with traditional Bandhej patch detailing adorned with delicate tar and resham work for a graceful ethnic touch. The lightweight linen shimmer fabric offers a soft texture with a subtle sheen, making it perfect for daytime functions, festive gatherings, poojas, and elegant celebrati",
    "fullDescription": "<p data-start=\"55\" data-end=\"411\">Bring home understated elegance with <em data-start=\"118\" data-end=\"131\">Ivory Grace</em>, a beautifully crafted linen shimmer saree designed for timeless festive styling. Featuring a soft ivory tone with elegant zari weaving borders, this saree is enhanced with traditional Bandhej patch detailing adorned with delicate tar and resham work for a graceful ethnic touch.</p>\n<p data-start=\"413\" data-end=\"699\">The lightweight linen shimmer fabric offers a soft texture with a subtle sheen, making it perfect for daytime functions, festive gatherings, poojas, and elegant celebrations. Paired with a matching same-fabric blouse, this saree creates a refined traditional look with effortless charm.</p>\n<p data-start=\"701\" data-end=\"779\">A perfect saree for women who love simple elegance with handcrafted detailing.</p>\n<p data-start=\"781\" data-end=\"1042\"><strong data-start=\"781\" data-end=\"795\">Highlights</strong><br data-start=\"795\" data-end=\"798\">• Soft Linen Shimmer Fabric<br data-start=\"825\" data-end=\"828\">• Elegant Zari Weaving Border<br data-start=\"857\" data-end=\"860\">• Traditional Bandhej Patch Work<br data-start=\"892\" data-end=\"895\">• Delicate Tar &amp; Resham Embroidery<br data-start=\"929\" data-end=\"932\">• Lightweight &amp; Comfortable Drape<br data-start=\"965\" data-end=\"968\">• Matching Same Fabric Blouse<br data-start=\"997\" data-end=\"1000\">• Perfect for Festive &amp; Traditional Wear</p>\n<p data-start=\"1044\" data-end=\"1083\"><strong data-start=\"1044\" data-end=\"1069\">Suggested Search Code</strong><br data-start=\"1069\" data-end=\"1072\">Ivory Grace</p>",
    "salePrice": 1730,
    "regularPrice": 1730,
    "category": "Silk",
    "status": "Sold out",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1340.jpg?v=1779720364",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1340.jpg?v=1779720364",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1323.jpg?v=1779720360",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1324.jpg?v=1779720361",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1296.jpg?v=1779720363",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1313.jpg?v=1779720364"
    ],
    "tags": [
      "#LinenShimmerSaree #IvoryGrace #DesignerSaree #FestiveWear #TraditionalSaree #BandhejWork #ReshamWork #ZariBorder #ElegantSaree #EthnicWear #PartyWearSaree #shophub"
    ],
    "featured": false,
    "bestSeller": false,
    "newArrival": false,
    "rating": 4,
    "reviewCount": 9,
    "createdAt": "2026-06-25T07:55:30.165Z"
  },
  {
    "title": "Kanjivaram Silk Saree with Diamond Work PINK",
    "slug": "kanjivaram-silk-saree-with-diamond-work-pink",
    "description": "Gracefully crafted Kanjivaram silk saree featuring rich woven patterns enhanced with elegant diamond work detailing. The luxurious sheen, vibrant Pink-gold tones, and intricately designed borders give this saree a grand festive and bridal appeal. Soft, regal, and timeless, this saree is perfect for weddings, receptions, festive celebrations, and special traditional occasions. Highlights Premium Kanjivaram Silk Fabric Elegant Diamond Work Detailing Rich Traditional Woven Design Luxurious Glossy F",
    "fullDescription": "<p data-start=\"87\" data-end=\"467\">Gracefully crafted Kanjivaram silk saree featuring rich woven patterns enhanced with elegant diamond work detailing. The luxurious sheen, vibrant Pink-gold tones, and intricately designed borders give this saree a grand festive and bridal appeal. Soft, regal, and timeless, this saree is perfect for weddings, receptions, festive celebrations, and special traditional occasions.</p>\n<h3 data-section-id=\"1au80px\" data-start=\"469\" data-end=\"485\">Highlights</h3>\n<ul data-start=\"486\" data-end=\"694\">\n<li data-section-id=\"1da50e5\" data-start=\"486\" data-end=\"520\">Premium Kanjivaram Silk Fabric</li>\n<li data-section-id=\"1v5v0vg\" data-start=\"521\" data-end=\"555\">Elegant Diamond Work Detailing</li>\n<li data-section-id=\"1tl2hro\" data-start=\"556\" data-end=\"589\">Rich Traditional Woven Design</li>\n<li data-section-id=\"zfs6kg\" data-start=\"590\" data-end=\"617\">Luxurious Glossy Finish</li>\n<li data-section-id=\"111tx3t\" data-start=\"618\" data-end=\"649\">Grand Festive &amp; Bridal Look</li>\n<li data-section-id=\"ghbm9s\" data-start=\"650\" data-end=\"694\">Perfect for Weddings &amp; Special Occasions</li>\n</ul>",
    "salePrice": 4990,
    "regularPrice": 6499,
    "category": "Silk",
    "status": "Available",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1221.jpg?v=1779375833",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1221.jpg?v=1779375833",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1222.jpg?v=1779375833",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1230.jpg?v=1779375840",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1237.jpg?v=1779375834",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1242.jpg?v=1779375836",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1213.jpg?v=1779375833"
    ],
    "tags": [
      "#BoutiqueCollection",
      "#BridalSaree",
      "#DesignerSaree",
      "#DiamondWorkSaree",
      "#EthnicFashion",
      "#FestiveCollection",
      "#FestiveWear",
      "#IndianFashion",
      "#KanjivaramSilkSaree",
      "#LuxurySaree",
      "#OrangeGoldSaree",
      "#PartyWearSaree",
      "#shophub",
      "#PremiumSilkSaree",
      "#RichWeave",
      "#RoyalLook",
      "#StatementDrape",
      "#TraditionalElegance",
      "#TrendingSarees",
      "#WeddingWearSaree"
    ],
    "featured": false,
    "bestSeller": false,
    "newArrival": false,
    "rating": 5,
    "reviewCount": 10,
    "createdAt": "2026-06-25T07:55:30.165Z"
  },
  {
    "title": "Black Beauty – Satin Chiffon Designer Saree",
    "slug": "black-beauty-satin-chiffon-designer-saree",
    "description": "Product Title Black Beauty – Satin Chiffon Designer Saree Product Description Step into effortless elegance with Black Beauty , a stunning satin chiffon saree crafted for graceful party and festive styling. Designed in an all-black tone, this saree features intricate hand beads and sequence work beautifully flowing in elegant jaal patterns across the body and pallu. The soft satin chiffon fabric gives a rich fall and lightweight comfort, while the detailed handcrafted border adds a sophisticated",
    "fullDescription": "<p data-start=\"0\" data-end=\"63\"><strong data-start=\"0\" data-end=\"17\">Product Title</strong><br data-start=\"17\" data-end=\"20\">Black Beauty – Satin Chiffon Designer Saree</p>\n<p data-start=\"65\" data-end=\"382\"><strong data-start=\"65\" data-end=\"88\">Product Description</strong><br data-start=\"88\" data-end=\"91\">Step into effortless elegance with <em data-start=\"126\" data-end=\"140\">Black Beauty</em>, a stunning satin chiffon saree crafted for graceful party and festive styling. Designed in an all-black tone, this saree features intricate hand beads and sequence work beautifully flowing in elegant jaal patterns across the body and pallu.</p>\n<p data-start=\"384\" data-end=\"703\">The soft satin chiffon fabric gives a rich fall and lightweight comfort, while the detailed handcrafted border adds a sophisticated designer finish. Paired with a matching full-work blouse in the same fabric, this saree creates a bold yet classy statement for evening events, receptions, parties, and special occasions.</p>\n<p data-start=\"705\" data-end=\"785\">A perfect choice for women who love modern glamour with timeless black elegance.</p>\n<p data-start=\"787\" data-end=\"1041\"><strong data-start=\"787\" data-end=\"801\">Highlights</strong><br data-start=\"801\" data-end=\"804\">• Soft Satin Chiffon Fabric<br data-start=\"831\" data-end=\"834\">• Elegant Hand Beads &amp; Sequence Work<br data-start=\"870\" data-end=\"873\">• Designer Jaal Pattern All Over<br data-start=\"905\" data-end=\"908\">• Fully Worked Matching Blouse<br data-start=\"938\" data-end=\"941\">• Lightweight &amp; Graceful Drape<br data-start=\"971\" data-end=\"974\">• Perfect for Parties &amp; Evening Wear<br data-start=\"1010\" data-end=\"1013\">• Rich Black Designer Look</p>\n<p data-start=\"1043\" data-end=\"1083\"><strong data-start=\"1043\" data-end=\"1068\"><span>NOTE : The blouse worn by the model might be for modelling purpose only. Check the image of the blouse piece to understand how the actual blouse piece looks like</span></strong></p>\n<p data-start=\"1043\" data-end=\"1083\"><strong data-start=\"1043\" data-end=\"1068\"><br></strong><br data-start=\"1068\" data-end=\"1071\"><br></p>",
    "salePrice": 4450,
    "regularPrice": 6999,
    "category": "Silk",
    "status": "Available",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1268.jpg?v=1779345966",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1268.jpg?v=1779345966",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1273.jpg?v=1779345966",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1266.jpg?v=1779345966",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1264.jpg?v=1779345966",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1269.jpg?v=1779345967"
    ],
    "tags": [
      "#BlackBeauty #BlackSaree #DesignerSaree #PartyWearSaree #SatinChiffonSaree #SequenceWorkSaree #HandWorkSaree #ElegantSaree #FestiveWear #PremiumLook #shophub #EveningWearSaree"
    ],
    "featured": false,
    "bestSeller": false,
    "newArrival": false,
    "rating": 4,
    "reviewCount": 3,
    "createdAt": "2026-06-25T07:55:30.165Z"
  },
  {
    "title": "Ivory Gold Saree with Heavy Zari Pallu & Ethnic Butta Design",
    "slug": "ivory-gold-saree-with-heavy-zari-pallu-ethnic-butta-design",
    "description": "Celebrate timeless tradition with this elegant cream gold saree, beautifully designed to reflect classic Indian craftsmanship. The saree features intricate traditional butta motifs across the body, complemented by a richly woven zari border and an eye-catching pallu with detailed patterns. The subtle contrast of pink along the border enhances its festive appeal while maintaining a graceful, sophisticated look. Crafted for comfort and elegance, this saree drapes effortlessly, making it a perfect ",
    "fullDescription": "<p>Celebrate timeless tradition with this elegant cream gold saree, beautifully designed to reflect classic Indian craftsmanship.</p>\n<p>The saree features intricate traditional butta motifs across the body, complemented by a richly woven zari border and an eye-catching pallu with detailed patterns. The subtle contrast of pink along the border enhances its festive appeal while maintaining a graceful, sophisticated look.</p>\n<p>Crafted for comfort and elegance, this saree drapes effortlessly, making it a perfect choice for weddings, festive occasions, and cultural celebrations.</p>\n<p>• Fabric: Soft Silk Blend<br>• Work: Traditional Zari Butta &amp; Rich Woven Border<br>• Color: Cream Gold with Pink Accents<br>• Occasion: Wedding, Festive, Traditional Wear<br>• Blouse: Included (Unstitched)</p>\n<p>Style Tip: Pair it with temple jewelry or emerald accessories for a regal traditional look.<br></p>",
    "salePrice": 3890,
    "regularPrice": 5200,
    "category": "Designer",
    "status": "Available",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1194.jpg?v=1779195358",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1194.jpg?v=1779195358",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1190.jpg?v=1779195355",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0557.jpg?v=1776804109",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0554.jpg?v=1776806507",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0558_bc024d52-51fd-40fe-ab01-35ca76bf8b75.jpg?v=1776806507",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1201.jpg?v=1779195354"
    ],
    "tags": [
      "elephant"
    ],
    "featured": false,
    "bestSeller": false,
    "newArrival": false,
    "rating": 5,
    "reviewCount": 4,
    "createdAt": "2026-06-25T07:55:30.165Z"
  },
  {
    "title": "Midnight Blue Satin Organza Designer Saree",
    "slug": "midnight-blue-satin-organza-saree",
    "description": "Step into effortless elegance with this stunning Satin Organza saree designed to make every occasion unforgettable. Featuring a rich midnight blue shade with intricate black sequence embroidery work, this saree beautifully blends modern glamour with timeless grace. The soft satin organza fabric gives a smooth flowy drape with a subtle glossy finish, while the heavily detailed embroidered border and designer pallu add a bold statement look. Perfect for cocktail parties, receptions, evening events",
    "fullDescription": "<p data-start=\"55\" data-end=\"348\">Step into effortless elegance with this stunning Satin Organza saree designed to make every occasion unforgettable. Featuring a rich midnight blue shade with intricate black sequence embroidery work, this saree beautifully blends modern glamour with timeless grace.</p>\n<p data-start=\"350\" data-end=\"702\">The soft satin organza fabric gives a smooth flowy drape with a subtle glossy finish, while the heavily detailed embroidered border and designer pallu add a bold statement look. Perfect for cocktail parties, receptions, evening events, festive celebrations, and special occasions, this saree is crafted for women who love classy yet striking fashion.</p>\n<p data-start=\"704\" data-end=\"854\"><span>This saree creates a complete luxurious party-wear look effortlessly.<br></span></p>\n<p data-start=\"856\" data-end=\"1108\"><strong data-start=\"856\" data-end=\"870\">Highlights</strong><br data-start=\"870\" data-end=\"873\">Premium Satin Organza Fabric<br data-start=\"901\" data-end=\"904\">Elegant Black Sequence Embroidery Work<br data-start=\"942\" data-end=\"945\">Rich Dual-Tone Midnight Blue Shade<br data-start=\"979\" data-end=\"982\">Designer Embroidered Border &amp; Pallu<br data-start=\"1017\" data-end=\"1020\">Soft Flowing Drape with Glossy Finish<br data-start=\"1057\" data-end=\"1060\">Perfect for Parties, Receptions &amp; Festive Wear<br><br><strong data-end=\"1068\" data-start=\"1043\"><span>NOTE : The blouse worn by the model might be for modelling purpose only. Check the image of the blouse piece to understand how the actual blouse piece looks like</span></strong><br></p>\n<p data-start=\"1110\" data-end=\"1157\"> </p>",
    "salePrice": 6999,
    "regularPrice": 9500,
    "category": "Silk",
    "status": "Available",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1174.jpg?v=1778946403",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1174.jpg?v=1778946403",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1129.jpg?v=1778946403",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1171.jpg?v=1779199058",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1178.jpg?v=1778946403",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1180.jpg?v=1778946403",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1182.jpg?v=1778946403",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1215.jpg?v=1779733180",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1216.jpg?v=1779733179"
    ],
    "tags": [
      "#BlueSaree",
      "#DesignerSaree",
      "#ElegantEthnicWear",
      "#EmbroideredSaree",
      "#FestiveWear",
      "#LuxurySaree",
      "#PartyWearSaree",
      "#shophub",
      "#ReceptionWear",
      "#SatinOrganzaSaree",
      "#SequenceWorkSaree",
      "#TrendySaree"
    ],
    "featured": false,
    "bestSeller": false,
    "newArrival": false,
    "rating": 4,
    "reviewCount": 5,
    "createdAt": "2026-06-25T07:55:30.165Z"
  },
  {
    "title": "Kanjivaram Silk Saree Yellow",
    "slug": "kanjivaram-silk-saree-yellow",
    "description": "Celebrate timeless elegance with this luxurious Kanjivaram Silk saree crafted to reflect rich traditional artistry and modern sophistication. Designed in a radiant mustard gold shade, the saree features beautiful self-weave floral patterns all over the body, paired with an intricately embellished scallop border that enhances its regal appeal. The rich silk texture and graceful sheen create a stunning drape, making it an ideal choice for weddings, festive occasions, receptions, and special celebr",
    "fullDescription": "<p data-start=\"77\" data-end=\"421\">Celebrate timeless elegance with this luxurious Kanjivaram Silk saree crafted to reflect rich traditional artistry and modern sophistication. Designed in a radiant mustard gold shade, the saree features beautiful self-weave floral patterns all over the body, paired with an intricately embellished scallop border that enhances its regal appeal.</p>\n<p data-start=\"423\" data-end=\"728\">The rich silk texture and graceful sheen create a stunning drape, making it an ideal choice for weddings, festive occasions, receptions, and special celebrations. The detailed craftsmanship along the border adds a refined designer touch while maintaining the classic charm of authentic Kanjivaram styling.</p>\n<p data-start=\"730\" data-end=\"812\">A perfect saree for women who love grand traditional looks with elegant detailing.</p>\n<h3 data-section-id=\"1au80px\" data-start=\"814\" data-end=\"830\">Highlights</h3>\n<ul data-start=\"831\" data-end=\"1026\">\n<li data-section-id=\"1da50e5\" data-start=\"831\" data-end=\"865\">Premium Kanjivaram Silk Fabric</li>\n<li data-section-id=\"102n4sh\" data-start=\"866\" data-end=\"902\">Elegant Self-Weave Floral Design</li>\n<li data-section-id=\"1xyd32m\" data-start=\"903\" data-end=\"935\">Designer Scallop Border Work</li>\n<li data-section-id=\"an7qpw\" data-start=\"936\" data-end=\"961\">Rich Traditional Look</li>\n<li data-section-id=\"1myjjsp\" data-start=\"962\" data-end=\"986\">Soft Luxurious Shine</li>\n<li data-section-id=\"isicuw\" data-start=\"987\" data-end=\"1026\">Perfect for Weddings &amp; Festive Wear</li>\n</ul>\n<h3 data-section-id=\"5sfuo0\" data-start=\"1028\" data-end=\"1055\"><br></h3>",
    "salePrice": 3500,
    "regularPrice": 5199,
    "category": "Silk",
    "status": "Available",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0735_71038a0a-e311-4ba2-95a5-fc5b682bbe2c.jpg?v=1778361416",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0735_71038a0a-e311-4ba2-95a5-fc5b682bbe2c.jpg?v=1778361416",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0747-2.jpg?v=1778361499",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0779.jpg?v=1778361415",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0743.jpg?v=1778361415"
    ],
    "tags": [
      "#DesignerSaree",
      "#ElegantEthnicWear",
      "#FestiveWear",
      "#GoldenSaree",
      "#KanjivaramSilkSaree",
      "#LuxurySaree",
      "#PartyWearSaree",
      "#shophub",
      "#PremiumCollection",
      "#SilkSaree",
      "#TraditionalSaree",
      "#WeddingWearSaree"
    ],
    "featured": false,
    "bestSeller": false,
    "newArrival": false,
    "rating": 5,
    "reviewCount": 6,
    "createdAt": "2026-06-25T07:55:30.165Z"
  },
  {
    "title": "Premium Satin Organza Saree with Hand Beads Work",
    "slug": "premium-satin-organza-saree-with-hand-beads-work",
    "description": "Grace meets elegance in this beautifully crafted Satin Organza saree designed for timeless sophistication. Featuring a soft glossy finish in a stunning peach-pink tone, this saree is adorned with delicate hand beads work spread elegantly across the body and enhanced with an intricately embellished border. The lightweight satin organza fabric gives a rich flowing drape while maintaining a graceful airy texture, making it a perfect choice for parties, festive occasions, receptions, and elegant eve",
    "fullDescription": "<p data-start=\"96\" data-end=\"402\">Grace meets elegance in this beautifully crafted Satin Organza saree designed for timeless sophistication. Featuring a soft glossy finish in a stunning peach-pink tone, this saree is adorned with delicate hand beads work spread elegantly across the body and enhanced with an intricately embellished border.</p>\n<p data-start=\"404\" data-end=\"607\">The lightweight satin organza fabric gives a rich flowing drape while maintaining a graceful airy texture, making it a perfect choice for parties, festive occasions, receptions, and elegant evening wear.</p>\n<p data-start=\"609\" data-end=\"680\">A subtle statement piece for women who love classy and refined fashion.</p>\n<h3 data-section-id=\"1au80px\" data-start=\"682\" data-end=\"698\">Highlights</h3>\n<ul data-start=\"699\" data-end=\"899\">\n<li data-section-id=\"14gmy8x\" data-start=\"699\" data-end=\"731\">Premium Satin Organza Fabric</li>\n<li data-section-id=\"xahftx\" data-start=\"732\" data-end=\"768\">Elegant Hand Beads Embellishment</li>\n<li data-section-id=\"1md8pgb\" data-start=\"769\" data-end=\"805\">Intricately Detailed Border Work</li>\n<li data-section-id=\"5t00w8\" data-start=\"806\" data-end=\"828\">Soft Glossy Finish</li>\n<li data-section-id=\"1fgmkly\" data-start=\"829\" data-end=\"864\">Lightweight &amp; Comfortable Drape</li>\n<li data-section-id=\"11o27c1\" data-start=\"865\" data-end=\"899\">Ideal for Party &amp; Festive Wear</li>\n</ul>",
    "salePrice": 3790,
    "regularPrice": 4949,
    "category": "Silk",
    "status": "Sold out",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1111.jpg?v=1778360215",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1111.jpg?v=1778360215",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1110.jpg?v=1778360215",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1113.jpg?v=1778360215",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1117.jpg?v=1778360215",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1120.jpg?v=1778360215",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1118.jpg?v=1778360215"
    ],
    "tags": [
      "#BeadsWorkSaree",
      "#DesignerSaree",
      "#ElegantSaree",
      "#FestiveCollection",
      "#HandWorkSaree",
      "#LuxuryEthnicWear",
      "#ModernTraditional",
      "#PartyWearSaree",
      "#PinkSaree",
      "#shophub",
      "#PremiumSaree",
      "#SatinOrganzaSaree"
    ],
    "featured": false,
    "bestSeller": false,
    "newArrival": false,
    "rating": 4,
    "reviewCount": 7,
    "createdAt": "2026-06-25T07:55:30.165Z"
  },
  {
    "title": "Satin Organza Saree with Resham & Glass Diamond Work",
    "slug": "satin-organza-saree-with-resham-glass-diamond-work",
    "description": "Elegant and graceful, this Satin Organza saree is designed to give a rich contemporary look with effortless charm. Crafted in a stunning emerald green shade, the saree features delicate Resham embroidery enhanced with shimmering glass diamond work across the body and borders. The soft satin-organza texture gives a beautiful glossy finish and lightweight drape, making it perfect for parties, festive gatherings, evening events, and special occasions. A perfect blend of sophistication and modern el",
    "fullDescription": "<p data-start=\"100\" data-end=\"552\">Elegant and graceful, this Satin Organza saree is designed to give a rich contemporary look with effortless charm. Crafted in a stunning emerald green shade, the saree features delicate Resham embroidery enhanced with shimmering glass diamond work across the body and borders. The soft satin-organza texture gives a beautiful glossy finish and lightweight drape, making it perfect for parties, festive gatherings, evening events, and special occasions.</p>\n<p data-start=\"554\" data-end=\"641\">A perfect blend of sophistication and modern elegance for women who love subtle luxury.</p>\n<h3 data-section-id=\"1au80px\" data-start=\"643\" data-end=\"659\">Highlights</h3>\n<ul data-start=\"660\" data-end=\"851\">\n<li data-section-id=\"14gmy8x\" data-start=\"660\" data-end=\"692\">Premium Satin Organza Fabric</li>\n<li data-section-id=\"pst2o7\" data-start=\"693\" data-end=\"724\">Intricate Resham Embroidery</li>\n<li data-section-id=\"1crkonr\" data-start=\"725\" data-end=\"755\">Elegant Glass Diamond Work</li>\n<li data-section-id=\"1fgmkly\" data-start=\"756\" data-end=\"791\">Lightweight &amp; Comfortable Drape</li>\n<li data-section-id=\"1vzbfti\" data-start=\"792\" data-end=\"814\">Rich Glossy Finish</li>\n<li data-section-id=\"rs5s2f\" data-start=\"815\" data-end=\"851\">Perfect for Party &amp; Festive Wear</li>\n</ul>",
    "salePrice": 3499,
    "regularPrice": 4549,
    "category": "Designer",
    "status": "Available",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1101.jpg?v=1778359802",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1101.jpg?v=1778359802",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1099.jpg?v=1778359801",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1104.jpg?v=1778359800",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1106.jpg?v=1778359801"
    ],
    "tags": [],
    "featured": false,
    "bestSeller": false,
    "newArrival": false,
    "rating": 5,
    "reviewCount": 8,
    "createdAt": "2026-06-25T07:55:30.165Z"
  },
  {
    "title": "Kanjivaram Silk Saree with Diamond Work",
    "slug": "kanjivaram-silk-saree-with-diamond-work",
    "description": "Gracefully crafted Kanjivaram silk saree featuring rich woven patterns enhanced with elegant diamond work detailing. The luxurious sheen, vibrant Red-gold tones, and intricately designed borders give this saree a grand festive and bridal appeal. Soft, regal, and timeless, this saree is perfect for weddings, receptions, festive celebrations, and special traditional occasions. Highlights Premium Kanjivaram Silk Fabric Elegant Diamond Work Detailing Rich Traditional Woven Design Luxurious Glossy Fi",
    "fullDescription": "<p data-start=\"87\" data-end=\"467\">Gracefully crafted Kanjivaram silk saree featuring rich woven patterns enhanced with elegant diamond work detailing. The luxurious sheen, vibrant Red-gold tones, and intricately designed borders give this saree a grand festive and bridal appeal. Soft, regal, and timeless, this saree is perfect for weddings, receptions, festive celebrations, and special traditional occasions.</p>\n<h3 data-section-id=\"1au80px\" data-start=\"469\" data-end=\"485\">Highlights</h3>\n<ul data-start=\"486\" data-end=\"694\">\n<li data-section-id=\"1da50e5\" data-start=\"486\" data-end=\"520\">Premium Kanjivaram Silk Fabric</li>\n<li data-section-id=\"1v5v0vg\" data-start=\"521\" data-end=\"555\">Elegant Diamond Work Detailing</li>\n<li data-section-id=\"1tl2hro\" data-start=\"556\" data-end=\"589\">Rich Traditional Woven Design</li>\n<li data-section-id=\"zfs6kg\" data-start=\"590\" data-end=\"617\">Luxurious Glossy Finish</li>\n<li data-section-id=\"111tx3t\" data-start=\"618\" data-end=\"649\">Grand Festive &amp; Bridal Look</li>\n<li data-section-id=\"ghbm9s\" data-start=\"650\" data-end=\"694\">Perfect for Weddings &amp; Special Occasions</li>\n</ul>",
    "salePrice": 4990,
    "regularPrice": 6499,
    "category": "Silk",
    "status": "Available",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1079.jpg?v=1778359108",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1079.jpg?v=1778359108",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1085_ed49060a-62ab-4f1c-88c3-45ca5ee0123b.jpg?v=1778359107",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1080.jpg?v=1778359109"
    ],
    "tags": [
      "#BoutiqueCollection",
      "#BridalSaree",
      "#DesignerSaree",
      "#DiamondWorkSaree",
      "#EthnicFashion",
      "#FestiveCollection",
      "#FestiveWear",
      "#IndianFashion",
      "#KanjivaramSilkSaree",
      "#LuxurySaree",
      "#OrangeGoldSaree",
      "#PartyWearSaree",
      "#shophub",
      "#PremiumSilkSaree",
      "#RichWeave",
      "#RoyalLook",
      "#StatementDrape",
      "#TraditionalElegance",
      "#TrendingSarees",
      "#WeddingWearSaree"
    ],
    "featured": false,
    "bestSeller": false,
    "newArrival": false,
    "rating": 4,
    "reviewCount": 9,
    "createdAt": "2026-06-25T07:55:30.165Z"
  },
  {
    "title": "Premium Giraffe Silk Saree with Zari Weaving Border",
    "slug": "premium-giraffe-silk-saree-with-zari-weaving-border",
    "description": "Elegantly crafted premium Giraffe Silk saree featuring a graceful floral self-weave design enhanced with a rich zari weaving border. The saree is beautifully embellished with intricate hand tube and stone work, adding a luxurious festive shimmer to the drape. The soft glossy texture and elegant fall make it a perfect choice for weddings, receptions, festive celebrations, and grand party occasions. Highlights Premium Giraffe Silk Fabric Elegant Floral Self Weave Design Rich Zari Weaving Border Ha",
    "fullDescription": "<p data-start=\"99\" data-end=\"499\">Elegantly crafted premium Giraffe Silk saree featuring a graceful floral self-weave design enhanced with a rich zari weaving border. The saree is beautifully embellished with intricate hand tube and stone work, adding a luxurious festive shimmer to the drape. The soft glossy texture and elegant fall make it a perfect choice for weddings, receptions, festive celebrations, and grand party occasions.</p>\n<h3>Highlights</h3>\n<ul>\n<li>Premium Giraffe Silk Fabric</li>\n<li>Elegant Floral Self Weave Design</li>\n<li>Rich Zari Weaving Border</li>\n<li>Hand Tube &amp; Stone Embellishments</li>\n<li>Soft Glossy Finish</li>\n<li>Perfect for Festive &amp; Wedding Wear</li>\n</ul>\n<h3>Delivery Information</h3>\n<p>Estimated delivery time: 3 to 4 <strong>business days</strong> from the date of order confirmation.</p>",
    "salePrice": 7999,
    "regularPrice": 8500,
    "category": "Silk",
    "status": "Available",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1048.jpg?v=1778358632",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1048.jpg?v=1778358632",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1051.jpg?v=1779199203",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1039.jpg?v=1778358632",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1059_fbef53bb-1ce3-4963-b36f-988e85029c96.jpg?v=1778358633",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1046.jpg?v=1778358633",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1056.jpg?v=1778358632"
    ],
    "tags": [
      "#BoutiqueCollection",
      "#DesignerSaree",
      "#ElegantStyle",
      "#FestiveCollection",
      "#IndianFashion",
      "#LuxurySaree",
      "#PartyWearSaree",
      "#shophub",
      "#PremiumCollection",
      "#PremiumSilkSaree",
      "#RoseGoldSaree",
      "#SoftSilkSaree",
      "#StatementDrape",
      "#StoneWorkSaree",
      "#TraditionalElegance",
      "#TrendingSarees",
      "#TubeWorkSaree",
      "#WeddingWearSaree",
      "#ZariBorderSaree"
    ],
    "featured": false,
    "bestSeller": false,
    "newArrival": false,
    "rating": 5,
    "reviewCount": 10,
    "createdAt": "2026-06-25T07:55:30.165Z"
  },
  {
    "title": "Kanjivaram Silk Saree with Diamond Work",
    "slug": "peach-premium-silk-saree-with-intricate-woven-pallu",
    "description": "Experience timeless tradition with a touch of modern elegance in this exquisite Kanjivaram Silk saree. Crafted with a rich silky texture and luxurious finish, this saree is beautifully enhanced with delicate diamond work that adds a graceful sparkle to every drape. Designed to make you stand out effortlessly, the saree features elegant woven patterns and a radiant sheen, making it perfect for weddings, festive celebrations, receptions, and grand occasions. The combination of classic Kanjivaram c",
    "fullDescription": "<p data-start=\"87\" data-end=\"352\">Experience timeless tradition with a touch of modern elegance in this exquisite Kanjivaram Silk saree. Crafted with a rich silky texture and luxurious finish, this saree is beautifully enhanced with delicate diamond work that adds a graceful sparkle to every drape.</p>\n<p data-start=\"354\" data-end=\"658\">Designed to make you stand out effortlessly, the saree features elegant woven patterns and a radiant sheen, making it perfect for weddings, festive celebrations, receptions, and grand occasions. The combination of classic Kanjivaram charm and subtle embellishments creates a sophisticated and regal look.</p>\n<p data-start=\"660\" data-end=\"743\">A perfect choice for women who love traditional elegance with contemporary glamour.</p>\n<h3 data-section-id=\"1au80px\" data-start=\"745\" data-end=\"761\">Highlights</h3>\n<ul data-start=\"762\" data-end=\"956\">\n<li data-section-id=\"1da50e5\" data-start=\"762\" data-end=\"796\">Premium Kanjivaram Silk Fabric</li>\n<li data-section-id=\"1nt8x1v\" data-start=\"797\" data-end=\"830\">Elegant Diamond Embellishment</li>\n<li data-section-id=\"1nr06me\" data-start=\"831\" data-end=\"859\">Rich Traditional Weaving</li>\n<li data-section-id=\"1gkb7ze\" data-start=\"860\" data-end=\"891\">Luxurious Soft Shine Finish</li>\n<li data-section-id=\"waaeqn\" data-start=\"892\" data-end=\"918\">Grand &amp; Graceful Drape</li>\n<li data-section-id=\"1684icu\" data-start=\"919\" data-end=\"956\">Ideal for Weddings &amp; Festive Wear</li>\n</ul>",
    "salePrice": 4999,
    "regularPrice": 6499,
    "category": "Designer",
    "status": "Available",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0981-2.jpg?v=1778363995",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0981-2.jpg?v=1778363995",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0977-2.jpg?v=1778363999",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0979-2.jpg?v=1778363994",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0977-2_edef58af-4da8-45e0-b57e-6228f11267a5.jpg?v=1778364017",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0985-2.jpg?v=1778364085"
    ],
    "tags": [],
    "featured": false,
    "bestSeller": false,
    "newArrival": false,
    "rating": 4,
    "reviewCount": 3,
    "createdAt": "2026-06-25T07:55:30.165Z"
  },
  {
    "title": "Yellow Russian Silk Viscose Saree with Position Prints",
    "slug": "yellow-russian-silk-viscose-saree-with-position-prints",
    "description": "Vibrant and eye-catching Russian silk viscose saree crafted with beautiful position prints that add a unique artistic charm to the drape. The rich yellow base paired with colorful traditional motifs creates a festive and elegant look. Soft, smooth, and comfortable to wear, this saree is perfect for festive occasions, family gatherings, cultural events, and stylish ethnic wear moments. Highlights Premium Russian Silk Viscose Fabric Elegant Position Print Design Rich Festive Color Combination Smoo",
    "fullDescription": "<p data-start=\"134\" data-end=\"521\">Vibrant and eye-catching Russian silk viscose saree crafted with beautiful position prints that add a unique artistic charm to the drape. The rich yellow base paired with colorful traditional motifs creates a festive and elegant look. Soft, smooth, and comfortable to wear, this saree is perfect for festive occasions, family gatherings, cultural events, and stylish ethnic wear moments.</p>\n<h3 data-section-id=\"1au80px\" data-start=\"523\" data-end=\"539\">Highlights</h3>\n<ul data-start=\"540\" data-end=\"751\">\n<li data-section-id=\"1swc8lg\" data-start=\"540\" data-end=\"579\">Premium Russian Silk Viscose Fabric</li>\n<li data-section-id=\"3702ua\" data-start=\"580\" data-end=\"613\">Elegant Position Print Design</li>\n<li data-section-id=\"w50h9e\" data-start=\"614\" data-end=\"648\">Rich Festive Color Combination</li>\n<li data-section-id=\"1om3ft6\" data-start=\"649\" data-end=\"679\">Smooth &amp; Comfortable Drape</li>\n<li data-section-id=\"106hxyr\" data-start=\"680\" data-end=\"713\">Lightweight and Easy to Carry</li>\n<li data-section-id=\"1cdvdpg\" data-start=\"714\" data-end=\"751\">Perfect for Festive &amp; Ethnic Wear</li>\n</ul>",
    "salePrice": 4999,
    "regularPrice": 6498,
    "category": "Silk",
    "status": "Sold out",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0953-2.jpg?v=1778186680",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0953-2.jpg?v=1778186680",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0955.jpg?v=1778186594",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0951.jpg?v=1778186597",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0950.jpg?v=1778186593",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0948.jpg?v=1778186593",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0949.jpg?v=1778186594"
    ],
    "tags": [
      "#BoutiqueCollection",
      "#ColorfulSaree",
      "#DesignerSaree",
      "#ElegantStyle",
      "#EthnicFashion",
      "#FestiveCollection",
      "#FestiveWear",
      "#IndianFashion",
      "#LuxuryLook",
      "#PartyWearSaree",
      "#PositionPrintSaree",
      "#shophub",
      "#PremiumSaree",
      "#PrintedSaree",
      "#RussianSilkSaree",
      "#StatementDrape",
      "#TraditionalWear",
      "#TrendingSarees",
      "#ViscoseSaree",
      "#YellowSaree"
    ],
    "featured": false,
    "bestSeller": false,
    "newArrival": false,
    "rating": 5,
    "reviewCount": 4,
    "createdAt": "2026-06-25T07:55:30.165Z"
  },
  {
    "title": "Teal Printed Everyday Wear Saree with Designer Border",
    "slug": "teal-printed-everyday-wear-saree-with-designer-border",
    "description": "Elegant and lightweight teal saree designed for comfortable everyday wear. Featuring delicate printed patterns all over the body with a stylish designer border, this saree offers the perfect blend of simplicity and grace. Easy to drape and comfortable for long hours, making it ideal for office wear, casual outings, small gatherings, and daily elegance. Highlights Soft &amp; Comfortable Fabric Elegant All-Over Print Stylish Designer Border Lightweight Daily Wear Saree Easy to Drape &amp; Maintain",
    "fullDescription": "<p data-start=\"134\" data-end=\"488\">Elegant and lightweight teal saree designed for comfortable everyday wear. Featuring delicate printed patterns all over the body with a stylish designer border, this saree offers the perfect blend of simplicity and grace. Easy to drape and comfortable for long hours, making it ideal for office wear, casual outings, small gatherings, and daily elegance.</p>\n<h3 data-section-id=\"1au80px\" data-start=\"490\" data-end=\"506\">Highlights</h3>\n<ul data-start=\"507\" data-end=\"690\">\n<li data-section-id=\"x5labd\" data-start=\"507\" data-end=\"536\">Soft &amp; Comfortable Fabric</li>\n<li data-section-id=\"qc5ecr\" data-start=\"537\" data-end=\"563\">Elegant All-Over Print</li>\n<li data-section-id=\"vife3l\" data-start=\"564\" data-end=\"591\">Stylish Designer Border</li>\n<li data-section-id=\"1sznhvy\" data-start=\"592\" data-end=\"624\">Lightweight Daily Wear Saree</li>\n<li data-section-id=\"5c04n4\" data-start=\"625\" data-end=\"653\">Easy to Drape &amp; Maintain</li>\n<li data-section-id=\"18awqmm\" data-start=\"654\" data-end=\"690\">Perfect for Office &amp; Casual Wear</li>\n</ul>",
    "salePrice": 1399,
    "regularPrice": 1799,
    "category": "Silk",
    "status": "Sold out",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1024.jpg?v=1778184620",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1024.jpg?v=1778184620",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1023.jpg?v=1778184619",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1030.jpg?v=1778184620",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC1025.jpg?v=1778184620"
    ],
    "tags": [
      "#AffordableElegance",
      "#AffordableFashion",
      "#BudgetFriendlyFashion",
      "#CasualWearSaree",
      "#ComfortWear",
      "#DailyWearSaree",
      "#DesignerBorderSaree",
      "#ElegantStyle",
      "#EthnicWear",
      "#EverydayWearSaree",
      "#IndianWear",
      "#LightweightSaree",
      "#OfficeWearSaree",
      "#shophub",
      "#PrintedSaree",
      "#SimpleAndElegant",
      "#SmartStyle",
      "#SoftFabricSaree",
      "#TealSaree",
      "#TraditionalLook"
    ],
    "featured": false,
    "bestSeller": false,
    "newArrival": false,
    "rating": 4,
    "reviewCount": 5,
    "createdAt": "2026-06-25T07:55:30.165Z"
  },
  {
    "title": "Designer Shaded Chiffon Silk Saree with Diamond work on Pallu & Border",
    "slug": "designer-shaded-chiffon-silk-saree",
    "description": "Elegant mustard yellow saree paired with a rich pink woven pallu, detailed zari motifs, and handcrafted tassels. A perfect festive and wedding wear drape designed for timeless elegance.",
    "fullDescription": "<p><span>Elegant mustard yellow saree paired with a rich pink woven pallu, detailed zari motifs, and handcrafted tassels. A perfect festive and wedding wear drape designed for timeless elegance.</span></p>",
    "salePrice": 3890,
    "regularPrice": 6299,
    "category": "Silk",
    "status": "Available",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0858.jpg?v=1778089426",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0858.jpg?v=1778089426",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0866.jpg?v=1778089428",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0865.jpg?v=1778089425",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0860.jpg?v=1778089425",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0874.jpg?v=1778089425"
    ],
    "tags": [
      "#BoutiqueCollection",
      "#ChiffonSilkSaree",
      "#DesignerSaree",
      "#DiamondWorkSaree",
      "#ElegantDrapes",
      "#ElegantStyle",
      "#EthnicFashion",
      "#FestiveCollection",
      "#FestiveLook",
      "#GraceInStyle",
      "#IndianWear",
      "#LuxurySaree",
      "#MustardSaree",
      "#PartyWearSaree",
      "#PinkSaree",
      "#shophub",
      "#PremiumSarees",
      "#SareeLove",
      "#ShadedFendyChiffon",
      "#ShadedSaree",
      "#SoftSilkFeel",
      "#StatementDrape",
      "#TraditionalLook",
      "#TrendingSarees",
      "#WeddingWearSaree",
      "#YellowPinkSaree"
    ],
    "featured": false,
    "bestSeller": false,
    "newArrival": false,
    "rating": 5,
    "reviewCount": 6,
    "createdAt": "2026-06-25T07:55:30.165Z"
  },
  {
    "title": "Shimmer Organza Saree in Champagne Gold with Glass Diamond Butta & Designer Border",
    "slug": "shimmer-organza-saree-in-champagne-gold-with-glass-diamond-butta-designer-border",
    "description": "Experience effortless elegance with this stunning shimmer net organza saree, crafted to bring a soft, graceful glow to your look. Adorned with delicate glass diamond butta work across the body, this saree sparkles subtly with every movement, creating a refined yet eye-catching appeal. The lightweight organza fabric offers a flowy drape, making it perfect for long events without compromising on comfort. Finished with a beautifully detailed border, this saree is ideal for weddings, receptions, and",
    "fullDescription": "<p>Experience effortless elegance with this stunning shimmer net organza saree, crafted to bring a soft, graceful glow to your look.</p>\n<p>Adorned with delicate glass diamond butta work across the body, this saree sparkles subtly with every movement, creating a refined yet eye-catching appeal. The lightweight organza fabric offers a flowy drape, making it perfect for long events without compromising on comfort.</p>\n<p>Finished with a beautifully detailed border, this saree is ideal for weddings, receptions, and evening celebrations where understated glamour stands out the most.</p>\n<p>• Fabric: Shimmer Net Organza<br>• Work: Glass Diamond Butta<br>• Feel: Lightweight &amp; Flowing<br>• Occasion: Party Wear, Wedding, Evening Events<br>• Blouse: Included (Unstitched)</p>\n<p>Style Tip: Pair it with statement earrings and soft curls for a dreamy, elegant look.<br></p>",
    "salePrice": 6999,
    "regularPrice": 9099,
    "category": "Designer",
    "status": "Available",
    "image": "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0640.jpg?v=1776803859",
    "images": [
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0640.jpg?v=1776803859",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0638.jpg?v=1776803859",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0646.jpg?v=1776802017",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0649.jpg?v=1776802017",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0641.jpg?v=1776802017",
      "https://source.unsplash.com/800x600/?fashion,clothing/s/files/1/0680/6536/1968/files/DSC0640_bcc04c1d-eec7-4974-8e07-a21573ee8650.jpg?v=1776802053"
    ],
    "tags": [],
    "featured": false,
    "bestSeller": false,
    "newArrival": false,
    "rating": 4,
    "reviewCount": 7,
    "createdAt": "2026-06-25T07:55:30.165Z"
  }
];



